media: 
  input: public/images
  output: /images

content:
  - name: homepage
    label: Homepage
    type: file
    path: content/index.md
    filename: index.md
    fields:
      - {name: title, label: Title, type: string}
      - name: videos
        label: Video
        type: object
        list: true
        fields:
          - {name: title, label: Title, type: string}
          - {name: portrait, label: Video Portrait, type: string}
          - {name: landscape, label: Video Landscape, type: string}

  - name: product
    label: Products
    type: collection
    path: content/product
    filename: "{fields.slug}.md"
    fields:
      - {name: slug, label: Slug, type: string}
      - {name: group, label: Group, type: string}
      - {name: collection, label: Collection, type:string}
      - {name: title, label: Title, type: string}
      - {name: description, label: Short Description, type: string}
      - {name: price, label: Price, type: string}
      - {name: payment_link, label: Payment Link, type: string}
      - name: images
        label: Images
        type: object
        list: true
        fields:
          - {name: title, label: Title, type: string}
          - {name: image, label: Image, type: image}

  - name: about
    label: About
    type: file
    path: content/about.md
    filename: about.md

