media: 
  input: "public/images"
  output: "/images"

content:
  - name: "homepage"
    label: "Page d’accueil"
    type: "file"
    path: "content/index.md"
    filename: "index.md"
    fields:
      - {name: "title", label: "Titre", type: "string"}
      - {name: "logo", label: "Logo", type: "image"}
      - name: "videos"
        label: "Vidéos"
        type: "object"
        list: true
        fields:
          - {name: "title", label: "Titre", type: "string"}
          - {name: "portrait", label: "Vidéo Portrait", type: "string"}
          - {name: "landscape", label: "Vidéo Paysage", type: "string"}
          - {name: "link", label: "Lien", type: "string"}
      - name: "images"
        label: "Images"
        type: "object"
        list: true
        fields:
          - {name: "title", label: "Titre", type: "string"}
          - {name: "image_portrait", label: "Fond Portrait", type: "image"}
          - {name: "image_landscape", label: "Fond Paysage", type: "image"}
          - {name: "link", label: "Lien", type: "string"}

  - name: "product"
    label: "Produits"
    type: "collection"
    path: "content/product"
    filename: "{fields.url}.md"
    fields:
      - {name: "url", label: "URL", type: "string"}
      - {name: "collection", label: "Collection", type: "string"}
      - {name: "title", label: "Titre", type: "string"}
      - {name: "description", label: "Description courte", type: "string"}
      - name: "variants"
        label: "Variantes"
        type: "object"
        list: true
        fields:
          - {name: "title", label: "Titre", type: "string"}
          - {name: "price", label: "Prix", type: "string"}
          - {name: "payment_link", label: "Lien de paiement", type: "string"}
          - {name: "color", label: "Couleur", type: "string"}
          - name: "images"
            label: "Images"
            type: "object"
            list: true
            fields:
              - {name: "image", label: "Image", type: "image"}

  - name: "collection"
    label: "Collection"
    type: "collection"
    path: "content/collection"
    filename: "{fields.url}.md"
    fields:
      - {name: "url", label: "URL", type: "string"}
      - {name: "title", label: "Titre", type: "string"}
      - {name: "description", label: "Description courte", type: "string"}
      - {name: "cover_image", label: "Image de couverture", type: "image"}
      - name: "images"
        label: "Images"
        type: "object"
        list: true
        fields:
          - {name: "image", label: "Image", type: "image"}

  - name: "about"
    label: "À propos"
    type: "file"
    path: "content/about.md"
    filename: "about.md"

  - name: "cgu"
    label: "CGU"
    type: "file"
    path: "content/cgu.md"
    filename: "cgu.md"

  - name: "cgv"
    label: "CGV"
    type: "file"
    path: "content/cgv.md"
    filename: "cgv.md"
