media: 
  input: public/images
  output: /images

content:
  - name: homepage
    label: Homepage
    type: file
    path: content/index.md
    filename: index.md
    fields:
      - {name: title, label: Title, type: string}
      - name: videos
        label: Video
        type: object
        list: true
        fields:
          - {name: title, label: Title, type: string}
          - {name: portrait, label: Video Portrait, type: string}
          - {name: landscape, label: Video Landscape, type: string}

  - name: product
    label: Products
    type: collection
    path: content/products
    filename: "{fields.slug}.md"
    fields:
      - {name: slug, label: Slug, type: string}
      - {name: title, label: Title, type: string}
      - {name: short-description, label: Short Description, type: string}
      - {name: long-description, label: Long Description, type: text}
      - {name: price, label: Price, type: string}
      - {name: payment-link, label: Payment Link, type: string}
      - {name: materials, label: Materials, type: string}
      - {name: dimensions, label: Dimensions, type: string}
      - name: images
        label: Images
        type: object
        list: true
        fields:
          - {name: title, label: Title, type: string}
          - {name: image, label: Image, type: image}
      - name: gallery
        label: Gallery / Carousel
        type: object
        list: true
        fields:
          - {name: caption, label: Caption, type: string}
          - {name: image, label: Image, type: image}
      - name: variations
        label: Variations
        type: object
        list: true
        fields:
          - {name: color, label: Color, type: string}
          - {name: variant-price, label: Price for Variation, type: string}
          - name: variant-images
            label: Images for Variation
            type: object
            list: true
            fields:
              - {name: title, label: Title, type: string}
              - {name: image, label: Image, type: image}

